### ISSUE TITLE
Create the new project

### ISSUE THREAD

**Issue by sych74** [innogames/ltc#14]
Hello!
I have installed the Jmeter-Control. How I can create a new project from dashboard?
I do not have the functionality in the controller for create a new project with a test plan.
<img width="1266" alt="screen shot 2018-11-09 at 12 46 09 pm" src="https://user-images.githubusercontent.com/17590698/48258495-d98ed080-e41d-11e8-85b2-d3fa0a98f915.png">

thanks,

**Comment by sych74** [comment]
ERROR:django.request: Internal Server Error: /online/tests_list (2018-11-09 12:37:28; exception.py:135)
Traceback (most recent call last):
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/JMeter-Control-Center-master/online/views.py", line 48, in tests_list
    jenkins_path = Configuration.objects.get(name='jenkins_path').value
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
administrator.models.DoesNotExist: Configuration matching query does not exist.

**Comment by v0devil** [comment]
Hi!
Please pull again

**Comment by sych74** [comment]
Hi!
Thanks, but I have any issues.
1. I have added Jmeter profile via dasboard
<img width="1262" alt="screen shot 2018-11-12 at 11 16 45 am" src="https://user-images.githubusercontent.com/17590698/48337834-b7d75880-e66c-11e8-8d76-e802b5a9aaaa.png">
2. Added SSH key for remote connect
<img width="1265" alt="screen shot 2018-11-12 at 11 17 07 am" src="https://user-images.githubusercontent.com/17590698/48337865-ce7daf80-e66c-11e8-9387-adcab2387107.png">
3. Created new project
<img width="1264" alt="screen shot 2018-11-12 at 11 17 36 am" src="https://user-images.githubusercontent.com/17590698/48337887-e0f7e900-e66c-11e8-9b6c-3dc5899e9410.png">
4. After starting the test, I get an error

ERROR:django.request: Internal Server Error: /controller/project/9/start_test/ (2018-11-12 09:13:50; exception.py:135)
Traceback (most recent call last):
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/JMeter-Control-Center-master/controller/views/controller_views.py", line 606, in start_test
    project_id=project_id).order_by("-id")[0]
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/db/models/query.py", line 289, in __getitem__
    return list(qs)[0]
IndexError: list index out of range

**Comment by v0devil** [comment]
Please pull and try again

**Comment by sych74** [comment]
Hi!
Thanks,
The next error

Traceback (most recent call last):
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/JMeter-Control-Center-master/controller/views/controller_views.py", line 648, in start_test
    for jmeter_param in jmeter_params:
TypeError: 'NoneType' object is not iterable
ERROR:django.server: "POST /controller/project/9/start_test/ HTTP/1.1" 500 16745 (2018-11-13 07:39:32; basehttp.py:124)
INFO:django.server: "GET /controller/ HTTP/1.1" 200 9465 (2018-11-13 07:39:32; basehttp.py:124)

**Comment by v0devil** [comment]
:( still much py2 leftovers. Plz pull

**Comment by sych74** [comment]
ERROR:django.request: Internal Server Error: /controller/project/9/start_test/ (2018-11-13 08:31:28; exception.py:135)
Traceback (most recent call last):
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/jelastic-python35/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/JMeter-Control-Center-master/controller/views/controller_views.py", line 704, in start_test
    text_file.write(output)
TypeError: write() argument must be str, not bytes
ERROR:django.server: "POST /controller/project/9/start_test/ HTTP/1.1" 500 16787 (2018-11-13 08:31:28; basehttp.py:124)

**Comment by v0devil** [comment]
Plz pull
