### ISSUE TITLE
Cant ssh with non 22 port

### ISSUE THREAD

**Issue by makorne** [innogames/ltc#21]
I start official docker and  try fill out port and ssh user by different means but always get error like this:

```
INFO:controller.views.controller_views: Try to connect via SSH to root@﻿xxx.xxx.xxx.xxx -p 32522 1 times (2019-08-14 18:34:54; controller_views.py:685)
JMeterControlCenter    | INFO:controller.views.controller_views: 1 time (2019-08-14 18:34:54; controller_views.py:690)
JMeterControlCenter    | INFO:django.server: "GET /controller/load_generators/get_data/ HTTP/1.1" 200 2 (2019-08-14 18:34:55; basehttp.py:124)
JMeterControlCenter    | INFO:django.server: "GET /controller/running_tests/get_data/ HTTP/1.1" 200 2 (2019-08-14 18:34:55; basehttp.py:124)
JMeterControlCenter    | ERROR:django.request: Internal Server Error: /controller/project/8/start_test/ (2019-08-14 18:34:56; exception.py:135)
JMeterControlCenter    | Traceback (most recent call last):
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
JMeterControlCenter    |     response = get_response(request)
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
JMeterControlCenter    |     response = self.process_exception_by_middleware(e, request)
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
JMeterControlCenter    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
JMeterControlCenter    |   File "/JMeter-Control-Center/controller/views/controller_views.py", line 694, in start_test
JMeterControlCenter    |     ssh.connect(hostname, key_filename=ssh_key)
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 340, in connect
JMeterControlCenter    |     to_try = list(self._families_and_addresses(hostname, port))
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 204, in _families_and_addresses
JMeterControlCenter    |     hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM
JMeterControlCenter    |   File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
JMeterControlCenter    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
JMeterControlCenter    | socket.gaierror: [Errno -2] Name or service not known
JMeterControlCenter    | ERROR:django.request: Internal Server Error: /controller/project/8/start_test/ (2019-08-14 18:34:56; exception.py:135)
JMeterControlCenter    | Traceback (most recent call last):
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
JMeterControlCenter    |     response = get_response(request)
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
JMeterControlCenter    |     response = self.process_exception_by_middleware(e, request)
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
JMeterControlCenter    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
JMeterControlCenter    |   File "/JMeter-Control-Center/controller/views/controller_views.py", line 694, in start_test
JMeterControlCenter    |     ssh.connect(hostname, key_filename=ssh_key)
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 340, in connect
JMeterControlCenter    |     to_try = list(self._families_and_addresses(hostname, port))
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 204, in _families_and_addresses
JMeterControlCenter    |     hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM
JMeterControlCenter    |   File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
JMeterControlCenter    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
```
How to fill it out right for JMCC? 

I can login with this key and port from this docker successfully.

**Comment by v0devil** [comment]
Hi, what do you try to execute there. I mean how can I re-produce it ?

**Comment by makorne** [comment]
```
Docker
To try to use this tool, you can try this docker-compose to deploy it quickly. https://github.com/arcmedia/JmeterControlCenter
```
docker-compose up,   filling out project and ssh key.
In Controller page -  filling out remote jmeter instances  like user@123.123.123.123 -p 1234 or 123.123.123.123:1234
Trying start, but always getting error.,,,,
