### ISSUE TITLE
No such file or directory 

### ISSUE THREAD

**Issue by aklimakin** [innogames/ltc#22]
Hi
I would like run test:
![Screenshot_30](https://user-images.githubusercontent.com/1586103/63274423-71242800-c2a8-11e9-9df7-4b7d2b8c77fd.png)

and I got some error:
`
JMeterControlCenter    | ERROR:django.request: Internal Server Error: /controller/project/3/start_test/ (2019-08-19 14:39:24; exception.py:135)
JMeterControlCenter    | Traceback (most recent call last):
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
JMeterControlCenter    |     response = get_response(request)
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
JMeterControlCenter    |     response = self.process_exception_by_middleware(e, request)
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
JMeterControlCenter    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
JMeterControlCenter    |   File "/JMeter-Control-Center/controller/views/controller_views.py", line 669, in start_test
JMeterControlCenter    |     result_file_destination
JMeterControlCenter    |   File "/JMeter-Control-Center/controller/views/controller_views.py", line 901, in prepare_test_plan
JMeterControlCenter    |     with open(testplan_dest, 'r') as src_jmx:
JMeterControlCenter    | FileNotFoundError: [Errno 2] No such file or directory: '/home/hybris/test.jmx'
JMeterControlCenter    | ERROR:django.request: Internal Server Error: /controller/project/3/start_test/ (2019-08-19 14:39:24; exception.py:135)
JMeterControlCenter    | Traceback (most recent call last):
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
JMeterControlCenter    |     response = get_response(request)
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
JMeterControlCenter    |     response = self.process_exception_by_middleware(e, request)
JMeterControlCenter    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
JMeterControlCenter    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
JMeterControlCenter    |   File "/JMeter-Control-Center/controller/views/controller_views.py", line 669, in start_test
JMeterControlCenter    |     result_file_destination
JMeterControlCenter    |   File "/JMeter-Control-Center/controller/views/controller_views.py", line 901, in prepare_test_plan
JMeterControlCenter    |     with open(testplan_dest, 'r') as src_jmx:
JMeterControlCenter    | FileNotFoundError: [Errno 2] No such file or directory: '/home/hybris/test.jmx'
`

I have this file on directory:
`
hybris@hybris:~$ ls -ld $PWD/*.jmx
-rwxrwxr-x 1 hybris hybris 113543 Aug 19 17:32 /home/hybris/test.jmx

`

**Comment by v0devil** [comment]
Hi, 
this is weird, cuz error message is saying the file is absent
